jobs:
  checkout:
    executor: python/default
    steps:
      - checkout
      - python/dist
 
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - checkout
      - python/test:
          pkg-manager: pipenv
          test-tool: pytest
      
