"""update user info

Revision ID: 159fa6db571b
Revises: 8b7d06b635a1
Create Date: 2020-10-01 21:10:14.016539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '159fa6db571b'
down_revision = '8b7d06b635a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'schoolID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_user_info_regionID'), 'user_info', ['regionID'], unique=False)
    op.drop_constraint('user_info_ibfk_1', 'user_info', type_='foreignkey')
    op.create_foreign_key(None, 'user_info', 'school_info', ['schoolID'], ['schoolID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_info', 'region_info', ['regionID'], ['regionID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.create_foreign_key('user_info_ibfk_1', 'user_info', 'region_info', ['schoolID'], ['regionID'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_info_regionID'), table_name='user_info')
    op.alter_column('user_info', 'schoolID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
