"""empty message

Revision ID: 23b102d937bf
Revises: fb25b3f55220
Create Date: 2020-12-06 01:09:32.515750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b102d937bf'
down_revision = 'fb25b3f55220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_info', sa.Column('viewNumber', sa.Integer(), nullable=True))
    op.add_column('univ_info', sa.Column('viewNumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('univ_info', 'viewNumber')
    op.drop_column('major_info', 'viewNumber')
    # ### end Alembic commands ###
