"""add table contest info

Revision ID: 30df4e31e798
Revises: f0c9e064b610
Create Date: 2020-10-13 02:32:55.033406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30df4e31e798'
down_revision = 'f0c9e064b610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_info',
    sa.Column('contestID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('imageUrl', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('content', sa.String(length=7000, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('area', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('sponsor', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('start', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('prize', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('firstPrize', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('homePage', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('contestID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_info')
    # ### end Alembic commands ###
