"""update user info

Revision ID: 3bc10d9f34f9
Revises: b06b01f85676
Create Date: 2020-10-01 20:53:44.568287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bc10d9f34f9'
down_revision = 'b06b01f85676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('email', sa.String(length=100, collation='utf8_unicode_ci'), nullable=False))
    op.add_column('user_info', sa.Column('gender', sa.Integer(), nullable=False))
    op.add_column('user_info', sa.Column('regionID', sa.Integer(), nullable=True))
    op.drop_column('user_info', 'userName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('userName', mysql.CHAR(collation='utf8_unicode_ci', length=20), nullable=False))
    op.drop_column('user_info', 'regionID')
    op.drop_column('user_info', 'gender')
    op.drop_column('user_info', 'email')
    # ### end Alembic commands ###
