"""update table

Revision ID: 40008dfd7a38
Revises: 1012a87c15ba
Create Date: 2020-10-21 15:37:17.188673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40008dfd7a38'
down_revision = '1012a87c15ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafeteria_info', sa.Column('curCafeMenu', sa.String(length=7000, collation='utf8_unicode_ci'), nullable=True))
    op.add_column('cafeteria_info', sa.Column('nextCafeMenu', sa.String(length=7000, collation='utf8_unicode_ci'), nullable=True))
    op.drop_column('cafeteria_info', 'month')
    op.drop_column('cafeteria_info', 'cafeMenu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafeteria_info', sa.Column('cafeMenu', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=7000), nullable=True))
    op.add_column('cafeteria_info', sa.Column('month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cafeteria_info', 'nextCafeMenu')
    op.drop_column('cafeteria_info', 'curCafeMenu')
    # ### end Alembic commands ###
