"""empty message

Revision ID: 527c0aa424d8
Revises: 
Create Date: 2020-09-30 18:13:45.583413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527c0aa424d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_article_communityID'), 'article', ['communityID'], unique=False)
    op.create_index(op.f('ix_article_userID'), 'article', ['userID'], unique=False)
    op.create_index(op.f('ix_school_info_regionID'), 'school_info', ['regionID'], unique=False)
    op.create_index(op.f('ix_user_info_schoolID'), 'user_info', ['schoolID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_schoolID'), table_name='user_info')
    op.drop_index(op.f('ix_school_info_regionID'), table_name='school_info')
    op.drop_index(op.f('ix_article_userID'), table_name='article')
    op.drop_index(op.f('ix_article_communityID'), table_name='article')
    # ### end Alembic commands ###
