"""empty message

Revision ID: 571a81ecfcba
Revises: 159fa6db571b
Create Date: 2020-10-05 15:52:14.751519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571a81ecfcba'
down_revision = '159fa6db571b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('replyID', sa.Integer(), nullable=False),
    sa.Column('nickName', sa.String(length=20, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('content', sa.String(length=5000, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('writtenTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('replyID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    # ### end Alembic commands ###
