"""add new table cafeteria_info

Revision ID: 5fb4f46e56b3
Revises: af6e99f3e85b
Create Date: 2020-10-01 01:30:56.482507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb4f46e56b3'
down_revision = 'af6e99f3e85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafeteria_info',
    sa.Column('schoolID', sa.Integer(), nullable=False),
    sa.Column('regionID', sa.Integer(), nullable=True),
    sa.Column('cafeMenu', sa.String(length=7000, collation='utf8_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['regionID'], ['region_info.regionID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schoolID')
    )
    op.create_index(op.f('ix_cafeteria_info_regionID'), 'cafeteria_info', ['regionID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cafeteria_info_regionID'), table_name='cafeteria_info')
    op.drop_table('cafeteria_info')
    # ### end Alembic commands ###
