"""empty message

Revision ID: 76e5b9ceb73d
Revises: dab351751e0f
Create Date: 2020-11-18 01:12:47.877882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e5b9ceb73d'
down_revision = 'dab351751e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_info', sa.Column('I_CODE', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True))
    op.add_column('school_info', sa.Column('SC_CODE', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_info', 'SC_CODE')
    op.drop_column('school_info', 'I_CODE')
    # ### end Alembic commands ###
