"""add version to cafemenu

Revision ID: 7a9e3f9d9c12
Revises: b077cc602d97
Create Date: 2020-10-09 06:27:49.430155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9e3f9d9c12'
down_revision = 'b077cc602d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafeteria_info', sa.Column('version', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafeteria_info', 'version')
    # ### end Alembic commands ###
