"""add liveshow table

Revision ID: 7c0b975042cd
Revises: d1b02fb7e475
Create Date: 2020-11-02 22:46:06.988039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = '7c0b975042cd'
down_revision = 'd1b02fb7e475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_show',
    sa.Column('liveShowID', sa.Integer(), nullable=False),
    sa.Column('univID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('content', sa.String(length=5000, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('heart', sa.Integer(), server_default=FetchedValue(), nullable=True),
    sa.Column('writtenTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['univID'], ['univ_info.univID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('liveShowID')
    )
    op.create_index(op.f('ix_live_show_univID'), 'live_show', ['univID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_show_univID'), table_name='live_show')
    op.drop_table('live_show')
    # ### end Alembic commands ###
