"""update user info

Revision ID: 8b7d06b635a1
Revises: 3bc10d9f34f9
Create Date: 2020-10-01 21:09:29.184225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b7d06b635a1'
down_revision = '3bc10d9f34f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'schoolID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('user_info_ibfk_1', 'user_info', type_='foreignkey')
    op.create_foreign_key(None, 'user_info', 'region_info', ['schoolID'], ['regionID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.create_foreign_key('user_info_ibfk_1', 'user_info', 'school_info', ['schoolID'], ['schoolID'], ondelete='CASCADE')
    op.alter_column('user_info', 'schoolID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
