"""upgrade database

Revision ID: 91054541ff7b
Revises: c487cbe197b2
Create Date: 2020-10-28 18:33:20.807949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91054541ff7b'
down_revision = 'c487cbe197b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_report', sa.Column('reportNum', sa.Integer(), nullable=True))
    op.add_column('article_report', sa.Column('reportUser', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_report', 'reportUser')
    op.drop_column('article_report', 'reportNum')
    # ### end Alembic commands ###
