"""empty message

Revision ID: 957f9d6b8756
Revises: a85951289b00
Create Date: 2020-11-18 03:00:21.809402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957f9d6b8756'
down_revision = 'a85951289b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('recommendCode', sa.String(length=20, collation='utf8_unicode_ci'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'recommendCode')
    # ### end Alembic commands ###
