"""add contest_info table end column

Revision ID: 9cbd7e73ecf4
Revises: 30df4e31e798
Create Date: 2020-10-13 02:56:18.480732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbd7e73ecf4'
down_revision = '30df4e31e798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_info', sa.Column('end', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest_info', 'end')
    # ### end Alembic commands ###
