"""add table like to

Revision ID: a4bc62444706
Revises: 1f15e73ddd04
Create Date: 2020-10-16 23:16:02.149393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bc62444706'
down_revision = '1f15e73ddd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_to_all',
    sa.Column('likeID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('articleID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articleID'], ['article_all.articleID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['user_info.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('likeID')
    )
    op.create_index(op.f('ix_like_to_all_articleID'), 'like_to_all', ['articleID'], unique=False)
    op.create_index(op.f('ix_like_to_all_userID'), 'like_to_all', ['userID'], unique=False)
    op.create_table('like_to_region',
    sa.Column('likeID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('articleID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articleID'], ['article_region.articleID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['user_info.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('likeID')
    )
    op.create_index(op.f('ix_like_to_region_articleID'), 'like_to_region', ['articleID'], unique=False)
    op.create_index(op.f('ix_like_to_region_userID'), 'like_to_region', ['userID'], unique=False)
    op.create_table('like_to_school',
    sa.Column('likeID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('articleID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articleID'], ['article_school.articleID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['user_info.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('likeID')
    )
    op.create_index(op.f('ix_like_to_school_articleID'), 'like_to_school', ['articleID'], unique=False)
    op.create_index(op.f('ix_like_to_school_userID'), 'like_to_school', ['userID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_to_school_userID'), table_name='like_to_school')
    op.drop_index(op.f('ix_like_to_school_articleID'), table_name='like_to_school')
    op.drop_table('like_to_school')
    op.drop_index(op.f('ix_like_to_region_userID'), table_name='like_to_region')
    op.drop_index(op.f('ix_like_to_region_articleID'), table_name='like_to_region')
    op.drop_table('like_to_region')
    op.drop_index(op.f('ix_like_to_all_userID'), table_name='like_to_all')
    op.drop_index(op.f('ix_like_to_all_articleID'), table_name='like_to_all')
    op.drop_table('like_to_all')
    # ### end Alembic commands ###
