"""empty message

Revision ID: a85951289b00
Revises: 76e5b9ceb73d
Create Date: 2020-11-18 02:55:04.768616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85951289b00'
down_revision = '76e5b9ceb73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommend',
    sa.Column('recommendID', sa.Integer(), nullable=False),
    sa.Column('newUserID', sa.Integer(), nullable=True),
    sa.Column('recommendUserID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['newUserID'], ['user_info.userID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendUserID'], ['user_info.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendID')
    )
    op.create_index(op.f('ix_user_recommend_newUserID'), 'user_recommend', ['newUserID'], unique=False)
    op.create_index(op.f('ix_user_recommend_recommendUserID'), 'user_recommend', ['recommendUserID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recommend_recommendUserID'), table_name='user_recommend')
    op.drop_index(op.f('ix_user_recommend_newUserID'), table_name='user_recommend')
    op.drop_table('user_recommend')
    # ### end Alembic commands ###
