"""upgrade database

Revision ID: a9174c56de8e
Revises: 74647b233ea1
Create Date: 2020-10-28 19:04:43.349452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9174c56de8e'
down_revision = '74647b233ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('banned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'banned')
    # ### end Alembic commands ###
