"""empty message

Revision ID: ab6c49cbda7f
Revises: ee686b9b709a
Create Date: 2020-10-05 15:52:42.470120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6c49cbda7f'
down_revision = 'ee686b9b709a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('communityID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reply_communityID'), 'reply', ['communityID'], unique=False)
    op.create_foreign_key(None, 'reply', 'community', ['communityID'], ['communityID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_index(op.f('ix_reply_communityID'), table_name='reply')
    op.drop_column('reply', 'communityID')
    # ### end Alembic commands ###
