"""school_info.schoolName longer

Revision ID: af6e99f3e85b
Revises: 62ccb97549d0
Create Date: 2020-09-30 21:29:19.380097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af6e99f3e85b'
down_revision = '62ccb97549d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_info', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_info', sa.Column('address', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    # ### end Alembic commands ###
