"""change rereply primary key name:


Revision ID: b077cc602d97
Revises: 6d3ff436b81b
Create Date: 2020-10-09 04:44:39.322714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b077cc602d97'
down_revision = '6d3ff436b81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rereply_all', sa.Column('replyID', sa.Integer(), nullable=False))
    op.drop_column('rereply_all', 'reReplyID')
    op.add_column('rereply_region', sa.Column('replyID', sa.Integer(), nullable=False))
    op.drop_column('rereply_region', 'reReplyID')
    op.add_column('rereply_school', sa.Column('replyID', sa.Integer(), nullable=False))
    op.drop_column('rereply_school', 'reReplyID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rereply_school', sa.Column('reReplyID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('rereply_school', 'replyID')
    op.add_column('rereply_region', sa.Column('reReplyID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('rereply_region', 'replyID')
    op.add_column('rereply_all', sa.Column('reReplyID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('rereply_all', 'replyID')
    # ### end Alembic commands ###
