"""add liveshow table

Revision ID: c0fb242c5961
Revises: d1562076b4bf
Create Date: 2020-11-02 23:09:29.521158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fb242c5961'
down_revision = 'd1562076b4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_live_show_userID'), 'live_show', ['userID'], unique=False)
    op.create_foreign_key(None, 'live_show', 'user_info', ['userID'], ['userID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'live_show', type_='foreignkey')
    op.drop_index(op.f('ix_live_show_userID'), table_name='live_show')
    # ### end Alembic commands ###
