"""upgrade database

Revision ID: c487cbe197b2
Revises: 40008dfd7a38
Create Date: 2020-10-28 17:48:50.323660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c487cbe197b2'
down_revision = '40008dfd7a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_report',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('articleID', sa.Integer(), nullable=True),
    sa.Column('communityID', sa.Integer(), nullable=True),
    sa.Column('articleType', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('content', sa.String(length=5000, collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('reportID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_report')
    # ### end Alembic commands ###
