"""add liveshow table

Revision ID: d1562076b4bf
Revises: 7c0b975042cd
Create Date: 2020-11-02 23:00:08.204363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1562076b4bf'
down_revision = '7c0b975042cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_show', sa.Column('major', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True))
    op.add_column('live_show', sa.Column('univTitle', sa.String(length=50, collation='utf8_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_show', 'univTitle')
    op.drop_column('live_show', 'major')
    # ### end Alembic commands ###
