"""upgrade

Revision ID: d1b02fb7e475
Revises: a9174c56de8e
Create Date: 2020-10-30 05:28:27.701560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b02fb7e475'
down_revision = 'a9174c56de8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('fcmToken', sa.String(length=200, collation='utf8_unicode_ci'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'fcmToken')
    # ### end Alembic commands ###
