"""add foreign constraint

Revision ID: d53b1b2f943f
Revises: ab6c49cbda7f
Create Date: 2020-10-06 08:41:35.696277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd53b1b2f943f'
down_revision = 'ab6c49cbda7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reply_userID', table_name='reply')
    op.drop_column('reply', 'userID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('userID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.create_index('ix_reply_userID', 'reply', ['userID'], unique=False)
    # ### end Alembic commands ###
