"""add signout user db table

Revision ID: d77a26a6b1c8
Revises: a4bc62444706
Create Date: 2020-10-17 04:51:15.160062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77a26a6b1c8'
down_revision = 'a4bc62444706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signout_user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('writtenTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signout_user')
    # ### end Alembic commands ###
