"""empty message

Revision ID: de809e1c42c5
Revises: d1d94c969d5e
Create Date: 2020-12-05 20:23:36.641398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de809e1c42c5'
down_revision = 'd1d94c969d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('univ_info', sa.Column('youtube', sa.String(length=500, collation='utf8_unicode_ci'), nullable=True))
    op.drop_column('univ_info', 'youtubue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('univ_info', sa.Column('youtubue', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=500), nullable=True))
    op.drop_column('univ_info', 'youtube')
    # ### end Alembic commands ###
