"""update student info

Revision ID: e3c7eb0de88a
Revises: 1f5736d970be
Create Date: 2020-10-13 10:21:58.684442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c7eb0de88a'
down_revision = '1f5736d970be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('authorized', sa.Integer(), nullable=True))
    op.add_column('user_info', sa.Column('regionName', sa.String(length=100, collation='utf8_unicode_ci'), nullable=False))
    op.add_column('user_info', sa.Column('schoolName', sa.String(length=100, collation='utf8_unicode_ci'), nullable=False))
    op.add_column('user_info', sa.Column('signupDate', sa.DateTime(), nullable=True))
    op.add_column('user_info', sa.Column('studentName', sa.String(length=100, collation='utf8_unicode_ci'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'studentName')
    op.drop_column('user_info', 'signupDate')
    op.drop_column('user_info', 'schoolName')
    op.drop_column('user_info', 'regionName')
    op.drop_column('user_info', 'authorized')
    # ### end Alembic commands ###
