"""add univ table

Revision ID: ebdc961a3dd2
Revises: 6e33cce4a7ad
Create Date: 2020-10-17 06:28:36.272069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdc961a3dd2'
down_revision = '6e33cce4a7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('univ_info', sa.Column('eduHomePage', sa.String(length=300, collation='utf8_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('univ_info', 'eduHomePage')
    # ### end Alembic commands ###
