"""empty message

Revision ID: ee686b9b709a
Revises: 571a81ecfcba
Create Date: 2020-10-05 15:52:28.640007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee686b9b709a'
down_revision = '571a81ecfcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('articleID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reply_articleID'), 'reply', ['articleID'], unique=False)
    op.create_foreign_key(None, 'reply', 'article', ['articleID'], ['articleID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_index(op.f('ix_reply_articleID'), table_name='reply')
    op.drop_column('reply', 'articleID')
    # ### end Alembic commands ###
