"""add student number per school

Revision ID: f0c9e064b610
Revises: 7a9e3f9d9c12
Create Date: 2020-10-12 22:43:29.244021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c9e064b610'
down_revision = '7a9e3f9d9c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_info', sa.Column('studentNum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_info', 'studentNum')
    # ### end Alembic commands ###
