"""add rereply table 


Revision ID: f8fc0a8b01b2
Revises: 13bcc409124d
Create Date: 2020-10-06 08:48:12.695469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fc0a8b01b2'
down_revision = '13bcc409124d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rereply',
    sa.Column('reReplyID', sa.Integer(), nullable=False),
    sa.Column('parentReplyID', sa.Integer(), nullable=True),
    sa.Column('articleID', sa.Integer(), nullable=True),
    sa.Column('communityID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('nickName', sa.String(length=20, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('content', sa.String(length=5000, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('writtenTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['articleID'], ['article.articleID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['communityID'], ['community.communityID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentReplyID'], ['reply.replyID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['user_info.userID'], ),
    sa.PrimaryKeyConstraint('reReplyID')
    )
    op.create_index(op.f('ix_rereply_articleID'), 'rereply', ['articleID'], unique=False)
    op.create_index(op.f('ix_rereply_communityID'), 'rereply', ['communityID'], unique=False)
    op.create_index(op.f('ix_rereply_parentReplyID'), 'rereply', ['parentReplyID'], unique=False)
    op.create_index(op.f('ix_rereply_userID'), 'rereply', ['userID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rereply_userID'), table_name='rereply')
    op.drop_index(op.f('ix_rereply_parentReplyID'), table_name='rereply')
    op.drop_index(op.f('ix_rereply_communityID'), table_name='rereply')
    op.drop_index(op.f('ix_rereply_articleID'), table_name='rereply')
    op.drop_table('rereply')
    # ### end Alembic commands ###
