"""empty message

Revision ID: fb25b3f55220
Revises: de809e1c42c5
Create Date: 2020-12-05 22:49:06.774042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb25b3f55220'
down_revision = 'de809e1c42c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_info',
    sa.Column('majorID', sa.Integer(), nullable=False),
    sa.Column('majorSeq', sa.Integer(), nullable=True),
    sa.Column('mClass', sa.String(length=100, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('gender', sa.String(length=20, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('employment_rate', sa.String(length=15, collation='utf8_unicode_ci'), nullable=True),
    sa.Column('avg_salary', sa.String(length=15, collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('majorID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_info')
    # ### end Alembic commands ###
